version: "3"
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=querent
      - POSTGRES_PASSWORD=querent
      - POSTGRES_DB=querent_test
    volumes:
      - ./querent/storage/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - querent
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "querent_test"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  querent:
    image: querent/rian:v1.0.1
    ports:
      - "1111:1111"
      - "2222:2222"
      - "3333:3333"
      - "10074:10074"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/external-config
      - ./content/models:/model
    environment:
      QUERENT_NODE_CONFIG: /external-config/querent.config.docker.yaml
    networks:
      - querent

networks:
  querent:
