version: "3"
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=querent
      - POSTGRES_PASSWORD=querent
      - POSTGRES_DB=querent_test
    volumes:
      - ./querent/storage/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - querent
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "querent_test"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password_neo
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - querent
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  querent:
    image: querent/rian:v4.3.0
    ports:
      - "1111:1111"
      - "2222:2222"
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./config:/external-config
      - ./content/models:/model
    environment:
      QUERENT_NODE_CONFIG: /external-config/querent.config.docker.yaml
    networks:
      - querent

networks:
  querent:
