/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
        /**
 * @returns { Promise<[boolean, UpdateResult | null]> }
 */
async getUpdateResult()  {
    return await TAURI_INVOKE("get_update_result");
},
/**
 * @returns { Promise<boolean> }
 */
async checkIfServiceIsRunning()  {
    return await TAURI_INVOKE("check_if_service_is_running");
},
/**
 * @returns { Promise<boolean> }
 */
async hasRianLicenseKey()  {
    return await TAURI_INVOKE("has_rian_license_key");
},
/**
 * @param { string } key
 * @returns { Promise<boolean> }
 */
async setRianLicenseKey(key)  {
    return await TAURI_INVOKE("set_rian_license_key", { key });
},
/**
 * @param { CollectorConfig[] } collectors
 * @returns { Promise<boolean> }
 */
async setCollectors(collectors)  {
    return await TAURI_INVOKE("set_collectors", { collectors });
},
/**
 * @returns { Promise<ListCollectorConfig> }
 */
async getCollectors()  {
    return await TAURI_INVOKE("get_collectors");
},
/**
 * @param { SemanticPipelineRequest } request
 * @returns { Promise<Result<SemanticPipelineResponse, string>> }
 */
async startAgnFabric(request)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_agn_fabric", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @returns { Promise<([string, SemanticPipelineRequest])[]> }
 */
async getRunningPipelines()  {
    return await TAURI_INVOKE("get_running_pipelines");
},
/**
 * @param { string } pipelineId
 * @returns { Promise<Result<null, string>> }
 */
async stopAgnFabric(pipelineId)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agn_fabric", { pipelineId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @param { string } searchQuery
 * @returns { Promise<Result<DiscoveryResponse, string>> }
 */
async sendDiscoveryRetrieverRequest(searchQuery)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_discovery_retriever_request", { searchQuery }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
}
    }

/** user-defined events **/


    /**
 * @type {typeof __makeEvents__<{
 * checkUpdateEvent: CheckUpdateEvent
 * checkUpdateResultEvent: CheckUpdateResultEvent
 * pinnedFromWindowEvent: PinnedFromWindowEvent
 * }>}
 */

    const __typedMakeEvents__ = __makeEvents__;

    export const events = __typedMakeEvents__({
    checkUpdateEvent: "check-update-event",
checkUpdateResultEvent: "check-update-result-event",
pinnedFromWindowEvent: "pinned-from-window-event"
    })

/** user-defined constants **/

export const universalConstant = 42;

/** user-defined types **/

/**
 * AzureCollectorConfig is a message to hold configuration for an Azure collector.
 * @typedef { { connection_string: string; container: string; credentials: string; prefix: string; id: string } } AzureCollectorConfig
 */

/**
 * @typedef { { azure: AzureCollectorConfig } | { gcs: GcsCollectorConfig } | { s3: S3CollectorConfig } | { jira: JiraCollectorConfig } | { drive: GoogleDriveCollectorConfig } | { email: EmailCollectorConfig } | { dropbox: DropBoxCollectorConfig } | { github: GithubCollectorConfig } | { slack: SlackCollectorConfig } | { news: NewsCollectorConfig } | { files: FileCollectorConfig } | { onedrive: OneDriveConfig } } Backend
 */

/**
 * @typedef { null } CheckUpdateEvent
 */

/**
 * @typedef { UpdateResult } CheckUpdateResultEvent
 */

/**
 * CollectorConfig is a message to hold configuration for a collector.
 * Defines a collector with a specific configuration.
 * @typedef { { name: string; backend: Backend | null } } CollectorConfig
 */

/**
 * @typedef { string } Custom
 */

/**
 * Response message containing insights discovered from the data
 * @typedef { { session_id: string; query: string; insights: Insight[] } } DiscoveryResponse
 */

/**
 * DropBoxCollectorConfig is a message to hold configuration for a DropBox collector.
 * @typedef { { dropbox_app_key: string; dropbox_app_secret: string; dropbox_refresh_token: string; folder_path: string; id: string } } DropBoxCollectorConfig
 */

/**
 * EmailCollectorConfig is a message to hold configuration for an Email collector.
 * @typedef { { imap_server: string; imap_port: number; imap_username: string; imap_password: string; imap_folder: string; id: string } } EmailCollectorConfig
 */

/**
 * FileCollectorConfig is a message to hold configuration for a file collector.
 * @typedef { { root_path: string; id: string } } FileCollectorConfig
 */

/**
 * @typedef { { entities: string[] } } FixedEntities
 */

/**
 * GCSCollectorConfig is a message to hold configuration for a GCS collector.
 * @typedef { { bucket: string; credentials: string; id: string } } GcsCollectorConfig
 */

/**
 * GithubCollectorConfig is a message to hold configuration for a Github collector.
 * @typedef { { github_username: string; github_access_token: string; repository: string; id: string } } GithubCollectorConfig
 */

/**
 * GoogleDriveCollectorConfig is a message to hold configuration for a Google Drive collector.
 * @typedef { { drive_client_id: string; drive_client_secret: string; drive_refresh_token: string; folder_to_crawl: string; id: string } } GoogleDriveCollectorConfig
 */

/**
 * Represents an insight discovered from the data
 * @typedef { { document: string; source: string; relationship_strength: string; sentence: string; tags: string } } Insight
 */

/**
 * JiraCollectorConfig is a message to hold configuration for a Jira collector.
 * @typedef { { jira_server: string; jira_username: string; jira_password: string; jira_api_token: string; jira_certfile: string; jira_keyfile: string; jira_verify: boolean; jira_project: string; jira_query: string; jira_start_at: number; jira_max_results: number; id: string } } JiraCollectorConfig
 */

/**
 * @typedef { { config: CollectorConfig[] } } ListCollectorConfig
 */

/**
 * NewsCollectorConfig is a message to hold configuration for a News collector.
 * @typedef { { api_key: string; query: string; from_date: string; to_date: string; language: string; domains: string; exclude_domains: string; sources: string; id: string } } NewsCollectorConfig
 */

/**
 * @typedef { { client_id: string; client_secret: string; redirect_uri: string; refresh_token: string; folder_path: string; id: string } } OneDriveConfig
 */

/**
 * @typedef { { pinned: boolean } } PinnedFromWindowEvent
 */

/**
 * S3CollectorConfig is a message to hold configuration for an S3 collector.
 * @typedef { { access_key: string; secret_key: string; region: string; bucket: string; id: string } } S3CollectorConfig
 */

/**
 * @typedef { { entities: string[] } } SampleEntities
 */

/**
 * @typedef { { collectors: string[]; fixed_entities: FixedEntities | null; sample_entities: SampleEntities | null; model: number | null; attention_threshold: number | null } } SemanticPipelineRequest
 */

/**
 * @typedef { { pipeline_id: string } } SemanticPipelineResponse
 */

/**
 * SlackCollectorConfig is a message to hold configuration for a Slack collector.
 * @typedef { { access_token: string; channel_name: string; cursor: string; include_all_metadata: boolean; includive: boolean; limit: number; id: string } } SlackCollectorConfig
 */

/**
 * @typedef { { version: string; currentVersion: string; body: string | null } } UpdateResult
 */


/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";

/** @typedef {typeof import("@tauri-apps/api/window").WebviewWindowHandle} __WebviewWindowHandle__ */

/**
 * @template T
 * @typedef {{
 *   listen: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
 *	 once: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
 *	 emit: T extends null
 *	   ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
 *     : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
 *	}} __EventObj__<T>
 */

/**
 * @template T,E
 * @typedef { { status: "ok", data: T } | { status: "error", error: E } } Result
 */

/**
 * @template {Record<string, any>} T
 * @param {Record<keyof T, string>} mappings
 * @returns {{
 * 	 [K in keyof T]: __EventObj__<T[K]> & {
 *	   (handle: __WebviewWindowHandle__): __EventObj__<T[K]>;
 *   };
 * }}
 */
function __makeEvents__(mappings) {
	return new Proxy(
		{},
		{
			get: (_, event) => {
				const name = mappings[event];

				new Proxy(() => {}, {
					apply: (_, __, [window]) => ({
						listen: (arg) => window.listen(name, arg),
						once: (arg) => window.once(name, arg),
						emit: (arg) => window.emit(name, arg),
					}),
					get: (_, command) => {
						switch (command) {
							case "listen":
								return (arg) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
