{
 "title": "Quester Metastore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Metastore requests rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(quester_metastore_requests_total[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Metastore requests duration (0.95)",
   "type": "timeseries",
   "description": "Duration in seconds",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(quester_metastore_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Metastore requests error rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(request_errors_total[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}