name: "Build Querent binary for macOS"
description: "Build React app and Rust binary for macOS with cargo build."
inputs:
  target:
    description: "Target"
    required: true
  version:
    description: "Binary version"
    required: true
  token:
    description: "GitHub access token"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "ASSET_FULL_NAME=rian-${{ inputs.version }}-${{ inputs.target }}" >> $GITHUB_ENV
      shell: bash
    - name: Install protoc
      run: brew install protobuf
      shell: bash
    - name: Install brew install libpq && brew link --force libpq
      run: |
        brew install libpq
        brew link --force libpq
        echo "export LIBPQ_INCLUDE_DIR=$(brew --prefix libpq)/include" >> $GITHUB_ENV
        echo "export LIBPQ_LIB_DIR=$(brew --prefix libpq)/lib" >> $GITHUB_ENV
        echo "export PQ_LIB_DIR=$(brew --prefix libpq)/lib" >> $GITHUB_ENV
      shell: bash
    - name: Install rustup
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
    - name: Install Rust Toolchain
      run: rustup toolchain install nightly
      shell: bash
    - name: Add target aarch64-apple-darwin
      if: "${{ inputs.target == 'aarch64-apple-darwin' }}"
      run: rustup target add aarch64-apple-darwin
      shell: bash
      working-directory: ./querent
    - name: Add target x86_64-apple-darwin
      if: "${{ inputs.target == 'x86_64-apple-darwin' }}"
      run: rustup target add x86_64-apple-darwin
      shell: bash
      working-directory: ./querent
    - name: Retrieve and export commit date, hash, and tags
      run: |
        echo "QUERENT_COMMIT_DATE=$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_TAGS=$(git tag --points-at HEAD | tr '\n' ',')" >> $GITHUB_ENV
      shell: bash
    - name: Build binary
      run: cargo build --release  --target ${{ matrix.target }} --features "license-check","openssl-support" --bin rian
      shell: bash
      working-directory: ./querent
      env:
        QUERENT_COMMIT_DATE: ${{ env.QUERENT_COMMIT_DATE }}
        QUERENT_COMMIT_HASH: ${{ env.QUERENT_COMMIT_HASH }}
        QUERENT_COMMIT_TAGS: ${{ env.QUERENT_COMMIT_TAGS }}
        POSTGRESQL_VERSION: 16
    - name: Bundle archive
      run: |
        make archive BINARY_FILE=target/${{ inputs.target }}/release/rian \
          BINARY_VERSION=${{ inputs.version }} ARCHIVE_NAME=${{ env.ASSET_FULL_NAME }}
      shell: bash
      working-directory: ./querent
    - name: Save binary archive for three days
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ASSET_FULL_NAME }}.tar.gz
        path: ./querent/${{ env.ASSET_FULL_NAME }}.tar.gz
