[build]
rustflags = ["--cfg", "tokio_unstable"]
rustdocflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-gnu]
# Targeting x86-64-v2 gives a ~2% performance boost while only
# disallowing Intel CPUs older than 2008 and AMD CPUs older than 2011.
# None of those very old CPUs are used in GCP
# (https://cloud.google.com/compute/docs/cpu-platforms). Unfortunately,
# AWS does not seem to disclose the exact CPUs they use.
rustflags = ["-C", "target-cpu=x86-64-v2", "--cfg", "tokio_unstable"]

# Windows static build
[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C", "target-feature=+crt-static",
	"-C", "link-arg=/NODEFAULTLIB:libvcruntimed.lib",
	"-C", "link-arg=/NODEFAULTLIB:vcruntime.lib",
	"-C", "link-arg=/NODEFAULTLIB:vcruntimed.lib",
	"-C", "link-arg=/NODEFAULTLIB:libcmtd.lib",
	"-C", "link-arg=/NODEFAULTLIB:msvcrt.lib",
	"-C", "link-arg=/NODEFAULTLIB:msvcrtd.lib",
	"-C", "link-arg=/NODEFAULTLIB:libucrt.lib",
	"-C", "link-arg=/NODEFAULTLIB:libucrtd.lib",
	"-C", "link-arg=/NODEFAULTLIB:ucrtd.lib",
	"-C", "link-arg=/DEFAULTLIB:libvcruntime.lib",
	"-C", "link-arg=/DEFAULTLIB:libcmt.lib",
	"-C", "link-arg=/DEFAULTLIB:ucrt.lib"
]
