# ============================ Node Configuration ==============================
#
# Website: https://github.com/querent-ai/querent
# Docs: https://github.com/querent-ai/querent-docs
#
# -------------------------------- General settings --------------------------------

# Config file format version.
version: 0.1

# Unique cluster ID. This is used to identify the cluster to which this node belongs.
cluster_id: querent-cluster
# Node identifier. This is used to identify this node within the cluster running semantic search.
node_id: querent-node
listen_address: 0.0.0.0
advertise_address: 0.0.0.0
gossip_listen_port: 2222
cpu_capacity: 5 # number of cores
memory_capacity: 1000 #MB
peer_seeds:

# -------------------------------- Restful Configuration --------------------------------
rest_config:
  listen_port: 1111
  cors_allow_origins:
    - "*"
  extra_headers:
    x-header-1: header-value-1
    x-header-2: header-value-2

grpc_config:
  listen_port: 50051
  max_message_size: 20 MB

# -------------------------------- Storage Configuration --------------------------------
storage_configs:
  - postgres:
      name: querent_test
      storage_type: index
      url: postgres://querent:querent@localhost/querent_test?sslmode=prefer
  - postgres:
      name: querent_test
      storage_type: vector
      url: postgres://querent:querent@localhost/querent_test?sslmode=prefer


# -------------------------------- Distributed Tracing Configuration --------------------------------
tracing:
  jaeger:
    enable_endpoint: true
    lookback_period_hours: 24
    max_trace_duration_secs: 600
    max_fetch_spans: 1000