name: "Build Querent binary for Windows with cargo cross"
description: "Build Quester Dashboard and Rust binary for Windows with cargo cross."
inputs:
  target:
    description: 'The target platform'
    required: true
  version:
    description: 'The release version'
    required: true
  token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "ASSET_FULL_NAME=querent-${{ inputs.version }}-${{ inputs.target }}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: "yarn"
        cache-dependency-path: ui/yarn.lock
    - run: yarn global add node-gyp
      shell: bash
    - run: cd quester && make build-ui
      shell: bash
    - name: copy build to quester/web/build
      run: cp -r ui/build quester/web
      shell: bash
    - name: Install rustup
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
    - name: Install Rust Toolchain
      run: rustup toolchain install nightly
      shell: bash

    # Add Windows-specific target
    - name: Add target x86_64-pc-windows-msvc
      if: "${{ inputs.target == 'x86_64-pc-windows-msvc' }}"
      run: rustup target add x86_64-pc-windows-msvc
      shell: bash

    - name: Install protoc
      run: choco install protoc
      shell: bash
    - name: Install postgres (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install postgresql12 --force --params '/Password:root'
        echo "C:\Program Files\PostgreSQL\12\bin" >> $GITHUB_PATH
        echo "C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_PATH
        echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
        echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
        echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
    - name: Install nasm
      uses: ilammy/setup-nasm@321e6ed62a1fc77024a3bd853deb33645e8b22c4
    - name: Install cross
      run: cargo install cross
      shell: bash
    - name: Retrieve and export commit date, hash, and tags
      run: |
        echo "QUERENT_COMMIT_DATE=$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_TAGS=$(git tag --points-at HEAD | tr '\n' ',')" >> $GITHUB_ENV
      shell: bash
    - name: Build binary
      run: cargo build --release  --target ${{ inputs.target }} --bin querent
      shell: bash
      env:
        QUERENT_COMMIT_DATE: ${{ env.QUERENT_COMMIT_DATE }}
        QUERENT_COMMIT_HASH: ${{ env.QUERENT_COMMIT_HASH }}
        QUERENT_COMMIT_TAGS: ${{ env.QUERENT_COMMIT_TAGS }}
      working-directory: ./quester
    - name: Bundle archive
      run: |
        cp target/$TARGET/release/querent.exe .
        zip -r $ASSET_FULL_NAME.zip querent.exe
      shell: bash
      env:
        ASSET_FULL_NAME: ${{ env.ASSET_FULL_NAME }}
      working-directory: ./quester
    - name: Save binary archive for three days
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ASSET_FULL_NAME }}
        retention-days: 3
        path: quester/$ASSET_FULL_NAME.zip
    - name: Upload archive
      uses: quickwit-inc/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        file: quester/$ASSET_FULL_NAME.zip
        overwrite: true
        tag_name: ${{ inputs.version }}
