name: Build and publish release packages

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (v#.#.#[-rc#])'
        required: true

env:
  INPUT_RELEASE_VERSION: ${{ github.event.inputs.release-version }}
jobs:
  build-macos-binaries:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cargo-build-macos-binary
        with:
          target: ${{ matrix.target }}
          version: ${{ env.INPUT_RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux-binaries:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cross-build-binary
        with:
          target: ${{ matrix.target }}
          version: ${{ env.INPUT_RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
