name: Release Docker Image
run-name: Cut Release ${{github.event.inputs.release-version || github.ref_name}}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version (v#.#.#[-rc#])"
        required: true

env:
  NEW_RELEASE_TAG_FROM_UI: ${{github.event.inputs.release-version || github.ref_name}}
  TEST_RUN: ${{startsWith(github.event.inputs.release-version || github.ref_name, 'v0.0.1')}}
  DOCKER_HUB_PROFILE: querent
  IMAGE_NAME: querent

jobs:
  build-and-publish-container-image:
    name: Build and publish container image
    runs-on: ubuntu-latest
    steps:
      - name: Validate Version Tag
        if: env.NEW_RELEASE_TAG_FROM_UI != ''
        shell: bash
        run: |
          version=${{env.NEW_RELEASE_TAG_FROM_UI}}
          echo "Release version entered in UI: $version"
          regex='^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-rc[1-9]\d*)?$'
          if [[ ! $version =~ $regex ]]; then
            echo "ERROR: Entered version $version is not valid."
            echo "Please use v#.#.#[-rc#] format."
            exit 1
          fi
          echo "valid-version=true" >> $GITHUB_OUTPUT
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up tags for cp image
        id: querent-tags
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
            prefix=api-,onlatest=true
          images: |
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}
          tags: |
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: |
            linux/amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Build and Push Querent Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{env.TEST_RUN != 'true'}}
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_PROFILE }}/${{ env.IMAGE_NAME }}:${{env.NEW_RELEASE_TAG_FROM_UI}}
