name: "Build Querent binary with cargo cross"
description: "Build Querent Dashboard and Rust binary with cargo cross."
inputs:
  target:
    description: "Target"
    required: true
  version:
    description: "Binary version"
    required: true
  token:
    description: "GitHub access token"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "ASSET_FULL_NAME=rian-${{ inputs.version }}-${{ inputs.target }}" >> $GITHUB_ENV
      shell: bash
    - name: Install rustup
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
    - name: Install Rust Toolchain
      run: rustup toolchain install nightly
      shell: bash
    - name: Add target x86_64-unknown-linux-gnu
      if: "${{ inputs.target == 'x86_64-unknown-linux-gnu' }}"
      run: rustup target add x86_64-unknown-linux-gnu
      shell: bash
    - name: Add target aarch64-unknown-linux-gnu
      if: "${{ inputs.target == 'aarch64-unknown-linux-gnu' }}"
      run: rustup target add aarch64-unknown-linux-gnu
      shell: bash
    - name: Install protoc
      run: sudo apt-get install protobuf-compiler
      shell: bash
    - name: Setup Tauri and Specta Dependencies
      run: sudo apt-get update && sudo apt-get install javascriptcoregtk-4.1  libsoup-3.0 librust-atk-dev libwebkit2gtk-4.1-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      shell: bash
    - name: Install cross
      run: cargo install cross
      shell: bash
    - name: Retrieve and export commit date, hash, and tags
      run: |
        echo "QUERENT_COMMIT_DATE=$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "QUERENT_COMMIT_TAGS=$(git tag --points-at HEAD | tr '\n' ',')" >> $GITHUB_ENV
      shell: bash
    - name: Build Qurent binary
      run: cargo build --release --target ${{ inputs.target }} --features "license-check","openssl-support" --bin rian
      shell: bash
      env:
        QUERENT_COMMIT_DATE: ${{ env.QUERENT_COMMIT_DATE }}
        QUERENT_COMMIT_HASH: ${{ env.QUERENT_COMMIT_HASH }}
        QUERENT_COMMIT_TAGS: ${{ env.QUERENT_COMMIT_TAGS }}
      working-directory: ./querent
    - name: Bundle archive
      run: |
        make archive BINARY_FILE=target/${{ inputs.target }}/release/rian \
          BINARY_VERSION=${{ inputs.version }} ARCHIVE_NAME=${{ env.ASSET_FULL_NAME }}
      shell: bash
      working-directory: ./querent
    - name: Save binary archive for three days
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ASSET_FULL_NAME }}.tar.gz
        path: ./querent/${{ env.ASSET_FULL_NAME }}.tar.gz


